GET http://localhost:3001

###
GET http://localhost:3001/api/blogs

###
GET http://localhost:3001/api/blogs/65758a5351784968b521fb13

###
POST http://localhost:3001/api/blogs
CONTENT-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFuZ2VsIiwiaWQiOiI2NTc4MmQxMTU3YWQ0MjZiZWE1ZWE0OGUiLCJpYXQiOjE3MDIzNzQ2ODh9.k-kfU6dn6BCR83bZY8_DTLmOj-TBJ6PbqqDSpkhUOZU

{ "title": "Safe Christmas treats",
"author": "CJ",
"url": "kinkku-for-everyone",
"likes": "3"
}

###
DELETE http://localhost:3001/api/blogs/65c9e2a7e0f57c6f141f25b5

###
PUT http://localhost:3001/api/blogs/6575fcc479200d024976029d
CONTENT-Type: application/json

{ 
"likes": "23" 
}