GET http://localhost:3001

###
GET http://localhost:3001/api/blogs

###
GET http://localhost:3001/api/blogs/65758a5351784968b521fb13

###
POST http://localhost:3001/api/blogs
CONTENT-Type: application/json

{ "title": "Nosework basics",
"author": "NT",
"url": "smells-everywhere",
"likes": "9" 
}

###
DELETE http://localhost:3001/api/blogs/6575f0387df6be9d91cd9932

###
PUT http://localhost:3001/api/blogs/6575fcc479200d024976029d
CONTENT-Type: application/json

{ "title": "Exercise requirements",
"author": "PK",
"url": "go-outside",
"likes": "9" 
}